### ISSUE TITLE
작성된 마크다운 텍스트 처리관련 문의 입니다.

### ISSUE THREAD

**Issue by choiyh44** [shiren/neon-editor#1]
관리자에서 에디터를 통하여 게시글을 작성하여 DB에 등록하고 
프론트에서 DB에 등록된 게시글을 조회하여 전시하는 구조의 프로그램 개발중입니다.
프로트 모듈 작성 시 질문사항 생겨서 문의 드립니다.

1) 게시글을 전시하려면 어떻게 해야하나요? 
2) 마크다운 텍스트를 일반 텍스트(plain text) 로 변환할 수 없나요?
3) 마크다운 텍스트를 html 텍스트(plain text) 로 변환할 수 없나요?

확인 부탁드립니다. 감사합니다.

**Comment by shiren** [comment]
https://github.com/chjj/marked

변환라이브러리를 이용합니다.~^^

에디터 컨셉이 기본적으로 마크다운 컨텐츠를 만드는게 주 목적인 에디터입니다.

html으로 값을 세팅하고 html으로 값을 가져오는 기능은 아직 구현되어있지 않습니다.

full버전의 js파일을 이용하시면 marked를  글로벌컨텍스트에서 바로 사용하실수 있습니다.

**Comment by kyuwoo-choi** [comment]
타이틀 제목을 제가 수정했습니다. 😢
외국인들도 같이 쓰는 만큼 이슈 관련되서 커밋이 올라갈때 적어도 추측은 할 수 있도록 하려합니다.

**Comment by moyiblog** [comment]
## How to get MD or HTML
