### ISSUE TITLE
Editor 관련 문의 드립니다.

### ISSUE THREAD

**Issue by kjh2165** [shiren/neon-editor#2]
안녕하세요.  네무소프트 김지혜입니다.

Toast Cloud Blog 개발 관련하여 Dooray editor을 사용하고 있는데요.
다음과 같은 이슈가 발생하여 문의 드리오니 확인 부탁드립니다.

1. 값 셋팅시 null 처리
null 값 셋팅시 오류가 발생하고 있습니다.
단, 임의적으로 blank를 넣으면 정상작동합니다.

2. image 경로 callback시 특수문자 처리
image 서버와 연동 후 이미지 경로를 에디터에 시팅시 특수문자가 들어가면
console창에 404(Not Found) 오류가 발생합니다.
물론 이미지도 보이지 않구요..

감사합니다.

**Comment by shiren** [comment]
1번문제는 지금 최신 커밋 버전에서는 발생하지 않고있습니다.

2번문제는 문제가 되는 이미지 경로 샘플하나만 부탁드립니다.

**Comment by kjh2165** [comment]
![](http://photo.toast.com/aaaadh/techblog/Tulips(4).jpg)

입니다.

**Comment by shiren** [comment]
혹시 플레이뮤지엄에서 근무하시나요?
http://photo.toast.com/aaaadh/techblog/Tulips(4).jpg
이 이미지가 404 not found뜬다는건가요?
404 not found 에러가 뜰때의 경로가 어떻게 되나요?

**Comment by shiren** [comment]
``` javascript
'addImageFileHook': function($form, callback) {
      callback('http://photo.toast.com/aaaadh/techblog/Tulips(4).jpg');
}
```

훅을 위와같이 하고 테스트 했을때 아무 문제 없었습니다.

**Comment by shiren** [comment]
이거 혹시 확인되거나 해결되었다면 코맨트 부탁드립니다~

**Comment by kjh2165** [comment]
플레이 뮤지엄 4층에 입구쪽에 있습니다.

GET http://photo.toast.com/aaaadh/techblog/Tulips(4 404 (Not Found)

이렇게 나옵니다.

**Comment by shiren** [comment]
특수문자때문이 아닌 괄호가 마크다운 문법과 겹처서 생기는 문제입니다.
괄호도 각각 lpar;과 rpar;로 인코딩이되야합니다

**Comment by shiren** [comment]
위지윅에서 다시 넘어올때 문제가 될수있으니 해결방법을 찾아보도록하겠습니다~

**Comment by shiren** [comment]
`![My Link](http://photo.toast.com/aaaadh/techblog/Tulips(4).jpg)`

우선은 http://이하의 내용은 `escape()`함수로 이스케이핑을 처리를 해서 사용하면 될것같습니다.
내부에서 사용하는 오픈소스에서 처리하는부분이라 바로 수정은 힘들것같습니다.

**Comment by kyuwoo-choi** [comment]
타이틀 제목을 제가 수정했습니다. 😢
외국인들도 같이 쓰는 만큼 이슈 관련되서 커밋이 올라갈때 적어도 추측은 할 수 있도록 하려합니다.
